services:
  redis:
    image: redis:7.0-alpine
    container_name: my_bot_redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  telebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telebot
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/${REDIS_DB}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs
      - ./app:/app
      - ./data:/data

volumes:
  redis_data: